### ISSUE TITLE
Enable continuous mode to Giganto producer

### ISSUE THREAD

**Issue by syncpark** [aicers/reproduce#191]
* Mode grow(continuous) should work in Giganto producer.
  * if continuous mode is true, REproduce should wait new messages and send it continuously.

**Comment by BLYKIM** [comment]
일반적인 log kind에 `-g true` arguments로는 잘 동작하고 있는데, zeek log로 raw data를 추가하는 쪽에 필요한 grow인가요?

**Comment by syncpark** [comment]
> 일반적인 log kind에 `-g true` option으로는 잘 동작하고 있는데, zeek log로 raw data를 추가하는 쪽에 필요한 grow인가요?

맞아요. Zeek 로그를 Giganto에 전송할 때는 이 옵션이 동작하지 않습니다. 파일의 끝에 도달하면 프로그램이 종료되네요.
