### ISSUE TITLE
Read data from ElasticSearch

### ISSUE THREAD

**Issue by syncpark** [aicers/reproduce#435]
Kx project:
- [ ] Read data from ElasticSearch and parse it and send the parsed result to Giganto

검토:
* elasticdump: 쿼리 지정해서 덤프하고, reproduce로 전송하는 작업을 반복하는 스크립트 혹은 Python 코드로 작성
* REST API: 실시간 조회해서 전송하는 기능을 개발할 경우. 조회 및 전송 속도가 너무 느릴 것으로 예상
* STREAM API: index 지정해서 가능한지 확실하지 않음.

**Comment by syncpark** [comment]
Joe에게 샘플 코드 있으니 그 방식으로 구현하는 것을 추천합니다.

**Comment by dongju93** [comment]
https://github.com/dongju93/sysmon-to-rocksdb/tree/csv_export_only
이 브랜치 사용하시면됩니다

빌드된 바이너리 파일을 우분투에서 실행 할 때 `Exec format error` 에러가 발생합니다
맥이나 윈도우에서는 문제 없음.

Cargo.toml 파일에 최적화를 위해 추가한 `[profile.release]` 때문일 수도 있습니다.
