### ISSUE TITLE
REproduce가 실행을 종료할 때 파일에 마지막으로 읽은 위치를 저장하도록 수정

### ISSUE THREAD

**Issue by syncpark** [aicers/reproduce#456]
REproduce가 실행을 종료할 때 파일에 마지막으로 읽은 위치(offset)를 저장하도록 수정.
이후 다시 실행할 경우 이전에 저장했던 위치(offset)로부터 다시 시작해야함.

**Comment by kimhanbeom** [comment]
`last_transfer_line_suffix` 로 해당 기능을 제공하고 있으므로 close 하겠습니다.
